### ISSUE TITLE
build of an image failed with exit code '1'

### ISSUE THREAD

**Issue by STUBA-rupr** [siemens/meta-iot2000#174]
Any hints how to succeed with the build of an image?
I tried to build the image kas-example-rt.yml and kas-example-swupdate.yml native or docker (I tried also checkout the tag V3.1.1.), tried also with 
`wget https://raw.githubusercontent.com/siemens/kas/2.6.3/kas-container` 
in OS Ubuntu 18.04 TLS, 20.04 TLS with the same result:
![image](https://user-images.githubusercontent.com/55546830/145392112-4a91b5e9-62e8-4090-b7a2-5b52ca26f0f1.png)
![image](https://user-images.githubusercontent.com/55546830/145392199-70ea3020-dfac-4dee-889e-6e0fb4197798.png)
little more success I got with editing  **kas-bsp.yml** with 2021-11-15 | build-appliance-image: Update to dunfell head revision yocto-.1.12dunfell-23.0.12

```
  poky:

    url: https://git.yoctoproject.org/git/poky

    refspec: 0839888394a6e42e96f9f0d201376eb38bc79b24

    layers:

      meta:

      meta-poky:

      meta-yocto-bsp:

```
for this case only node-red failed.

Any hints how can I succeed?
